In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.impute import SimpleImputer

In [4]:
ecomshop = pd.read_csv("shop_smart_ecommerce.csv")

In [5]:
ecomshop.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [6]:
ecomshop.shape

(12330, 18)

In [7]:
ecomshop.isnull().any()

Administrative             False
Administrative_Duration    False
Informational              False
Informational_Duration     False
ProductRelated             False
ProductRelated_Duration    False
BounceRates                False
ExitRates                  False
PageValues                 False
SpecialDay                 False
Month                      False
OperatingSystems           False
Browser                    False
Region                     False
TrafficType                False
VisitorType                False
Weekend                    False
Revenue                    False
dtype: bool

In [8]:
print(ecomshop.dtypes)

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

In [10]:
le = LabelEncoder()
ecomshop["Month"]= le.fit_transform(ecomshop["Month"])
ecomshop["VisitorType"]= le.fit_transform(ecomshop["VisitorType"])

In [11]:
ecomshop.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,1,1,1,1,2,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,2,1,2,2,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,4,1,9,3,2,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,2,3,2,2,4,2,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,2,3,3,1,4,2,True,False

In [15]:
x= ecomshop.drop("Revenue",axis=1)
y= ecomshop[["Revenue"]]

In [17]:
num_features = x.select_dtypes(include=["int64", "float64"]).columns

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [20]:
scaler = StandardScaler()
x_train_scale = scaler.fit_transform(x_train)
x_test_scale = scaler.transform(x_test)

In [21]:
print(x_train_scale)

[[ 1.7120884   3.62474482 -0.39578211 ... -0.51585403  0.40716739
  -0.5492383 ]
 [-0.69829357 -0.45234111 -0.39578211 ... -0.76491836  0.40716739
   1.82070333]
 [-0.69829357 -0.45234111 -0.39578211 ... -0.51585403  0.40716739
  -0.5492383 ]
 ...
 [-0.69829357 -0.45234111 -0.39578211 ... -0.01772538  0.40716739
   1.82070333]
 [-0.69829357 -0.45234111 -0.39578211 ... -0.51585403  0.40716739
   1.82070333]
 [-0.39699582 -0.13218756 -0.39578211 ...  0.97853192 -2.49478287
   1.82070333]]

In [22]:
model = DecisionTreeClassifier(max_depth= 6,
                               min_samples_split = 50,
                               min_samples_leaf=25,
                               random_state=42,
                               class_weight="balanced")

In [23]:
model.fit(x_train_scale,y_train)
y_pred = model.predict(x_test_scale)

In [25]:
from sklearn.metrics import f1_score,classification_report,confusion_matrix
print("f1Score:",f1_score(y_test,y_pred))
print("classification report:",classification_report(y_test,y_pred))
print("confusion_matrix:",confusion_matrix(y_test,y_pred))

f1Score: 0.6082089552238806
classification report:               precision    recall  f1-score   support

       False       0.97      0.83      0.89      2084
        True       0.47      0.85      0.61       382

    accuracy                           0.83      2466
   macro avg       0.72      0.84      0.75      2466
weighted avg       0.89      0.83      0.85      2466

confusion_matrix: [[1720  364]
 [  56  326]]

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

model = DecisionTreeClassifier()

param_grid = {
    "max_depth": [4, 6, 8],
    "min_samples_leaf": [20, 30, 50]
}

grid = GridSearchCV(
    model,
    param_grid,
    scoring="f1",
    cv=5,
    
)

grid.fit(x_train_scale, y_train)

print("Best F1:", grid.best_score_)
print("Best params:", grid.best_params_)

Best F1: 0.6448367044552434
Best params: {'max_depth': 8, 'min_samples_leaf': 50}